sudo: false
language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
install: pip install tox-travis
before_script: # configure a headless display to test plot generation
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start
script: tox
after_success:
- pip install coveralls
- coverage run --source=caf_verilog setup.py test
- coveralls